server:
  port: 8080
spring:
  application:
    name: tripPlanner
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: privet
    platform: POSTGRESQL
hibernate:
  hbm2ddl:
    auto: update
    show_sql: true
    format_sql: false